name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        run: |
          mvn -v
          echo "Maven and Java 17 setup complete"

      - name: Compile the project
        run: mvn clean compile --batch-mode --errors --fail-fast --show-version

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run unit tests
        run: mvn test --batch-mode --errors --fail-fast --show-version

      - name: Upload JUnit test results
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-reports
          path: target/surefire-reports/*.xml

  coverage:
    name: Run JaCoCo Coverage
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run JaCoCo coverage report
        run: mvn jacoco:prepare-agent test jacoco:report jacoco:check@check --batch-mode --errors --fail-fast --show-version

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-coverage-report
          path: target/site/jacoco/

  package:
    name: Build Package
    runs-on: ubuntu-latest
    needs: coverage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Package the project
        run: mvn package --batch-mode --errors --fail-fast --show-version
